apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-be-3
spec:
  capacity:
    storage: 2Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: nfs
  mountOptions:
    - nfsvers=4.1
  nfs:
    path: /data/nfs/pv-be3
    server: nfs-server
