apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: be-statefulset
spec:
  serviceName: facts
  replicas: 3
  selector:
    matchLabels:
      app: be
  template:
    metadata:
      labels:
        app: be
    spec:
      containers:
        - name: be-container
          image: shekeriev/k8s-facts
          ports:
            - containerPort: 5000
              protocol: TCP
          volumeMounts:
            - name: data
              mountPath: /data
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes:
          - ReadWriteOnce
        storageClassName: nfs
        resources:
          requests:
            storage: 2Gi
