apiVersion: v1
kind: Pod
metadata:
  name: homework-1
  namespace: homework
  labels:
    app: hw
  annotations:
    purpose: homework
spec:
  containers:
    - name: oracle
      image: shekeriev/k8s-oracle
