apiVersion: v1
kind: Pod
metadata:
  name: listener
  namespace: homework
  labels:
    app: listener
spec:
  containers:
    - name: listener
      image: shekeriev/k8s-listener
      ports:
        - containerPort: 5000
