apiVersion: v1
kind: ResourceQuota
metadata:
  name: projectx-quota
  namespace: projectx
spec:
  hard:
    requests.cpu: "1500m"
    requests.memory: "1536Mi"
    limits.cpu: "3"
    limits.memory: "3Gi"

    pods: "5"
    services: "3"
    count/deployments.apps: "3"
    count/replicasets.apps: "5"
